catalog:
  locations:
    - type: file
      target: /usr/src/app/catalog/components.yaml
    - type: file
      target: /usr/src/app/catalog/apis.yaml
    - type: file
      target: /usr/src/app/catalog/systems.yaml
    - type: file
      target: /usr/src/app/catalog/groups.yaml
    - type: file
      target: /usr/src/app/templates/java-service/template.yaml
